--- #YAML:1.0
name:               Image-Magick-Thumbnail-PDF
version:            1.13
abstract:           make thumbnail of a page in a pdf document
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Cwd:                  0
    File::Copy:           0
    File::Path:           0
    File::Which:          0
    Getopt::Std:          1
    Image::Magick:        0
    Image::Magick::Thumbnail:  0
    Smart::Comments:      0
    Test::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
