# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Image-Magick-Thumbnail-PDF
version:      1.04
version_from: lib/Image/Magick/Thumbnail/PDF.pm
installdirs:  site
requires:
    File::Copy:                    0
    File::Path:                    0
    Smart::Comments:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
